[pytest]
markers =
    unit: unit-level tests (single components behaviour)
    integration: integration-level tests (full library workflow, may use filesystem, network or be slow)

    s3: test on S3 bucket sources using moto library to mock S3