[pytest]
markers =
    unit: unit-level tests (single components behaviour)
    integration: integration-level tests (full library workflow, may use filesystem, network or be slow)

    provider: tests on the provider package
    component_provider: tests on the provider/component package
    resource_provider: tests on the provider/resource package

    settings: tests on the settings package

    parser: tests on the parser package
    config_parser: tests on the parser/config package 
    settings_parser: tests on the parser/settings package 
    template_parser: tests on the parser/template package 
    schema_parser: tests on the parser/schema package 
    variant_parser: tests on the parser/variant package 

    source: tests on the source package 
    aws: tests on aws sources using the moto mocking library

    executor: tests on the executor package

    engine: tests on the engine package

    template: tests on the template package
    compiler: tests on the compiler package
    renderer: tests on the renderer package
