[pytest]
markers =
    unit: unit-level tests (single components behaviour)
    integration: integration-level tests (full library workflow, may use filesystem, network or be slow)

    settings: tests on the settings package 

    source: tests on the source package 
    aws: tests on aws sources using the moto mocking library

    engine: tests on the engine package

    template: tests on the template package
    compiler: tests on the compiler package
    renderer: tests on the renderer package
